# FILE INFORMATIONS
title = "reduced TOML config file"
author = "Clement DECOOPMAN"


# PROJECT
[project]
name = "Virus propagation simulator"
description = "Simulate a virus propagation by using discrete events"
version = "1.0"
updated = "01/05/2020"

    [[project.authors]]
    name = "Clement DECOOPMAN"
    email = "clemdecoop.dev@gmail.com"

    [[project.authors]]
    name = "Evan Dadure"
    email = "evan.dadure@gmail.com"

    [[project.authors]]
    name = "Maxence Personaz"
    email = "maxenceperso@gmail.com"


# SIMULATION ENVIRONMENT
[simulation]
nb_cycle = 1            # number of cycles in the simulation
duration = 100           # period of each cycle in hours
population = 2000      # total number of people in the environment
infected_pop = 2        # numbre of infected people at the start    (We'll either choose this one or infected_pop)
infected_rate = 0.01     # rate of infected people at the start      (We'll either choose this one or infected_rate)
hc_rate = 0.2           # rate of healty carrier
mask_rate = 0.5         # rate of people who wear a safety mask against the virus
vaccination_rate = 0    # rate of people who have been vaccinated
confinement = false     # enable confinement (true / false)
nb_masks = 625          # base amount of masks available in each container/store

    # Virus
    [simulation.virus]
    name = "COVID-19"
    infectivity = 0.03         # base probability of getting infected
    mortality = 1              # base probability of death
    incubation = 33            # period in hours between infection and first appearance of symptoms
    infect_incr = false        # infection increased during incubation period (true / false)
    sick_time = 336            # period between the first appearance of symptoms and healing/death
    infectivity_time = 50    # period in hours during which the virus remains contagious
    immunity_time = 72       # period in hours during which the virus can't be transmitted
    incubation_rate = 1.3   # When in incubation, the infectivity is multiplied by this rate 
    sickness_rate = 0.7     # When in sickness, the infectivity is multiplied by this rate

    # People
    [simulation.people]
    trip_freq = [1, 60]          # number of times a person goes outside during the simulation cycle
    trip_duration = [1, 8]       # period of each trip in hours
    nb_meeting = [10, 20]         # interval of people met on every trip
